Repository Icinga/ipl-orm, pull requests merged in 2022-05, with the labels that each got.

#47 Emit event after assembling a Select object for a Query
  src/Query.php
Labels: enhancement, cla/signed

#57 Revert "Don't perform subquery filter on utilized()d relations"
  src/Compat/FilterProcessor.php
Labels: cla/signed

#61 FilterProcessor: Support `ipl\Stdlib\Filter\Like` and `\Unlike`
  src/Compat/FilterProcessor.php
Labels: cla/signed

#49 Hydrator: Require `ipl\Orm\Query` in the constructor
  src/Hydrator.php
  src/Query.php
Labels: cla/signed

#55 Do not automatically fetch side load queries
  src/Hydrator.php
Labels: bug, cla/signed

#54 PropertiesWithDefaults: Support iteration
  src/Common/PropertiesWithDefaults.php
  src/Model.php
Labels: cla/signed

#53 Resolver: Support rewrite behaviors also on relations
  src/Resolver.php
Labels: enhancement, cla/signed

#56 Allow order by aliased expressions
  src/Query.php
  src/Resolver.php
  tests/ApiIdentity.php
  tests/QueryTest.php
  tests/SqlTest.php
  tests/TestModelWithAliasedColumns.php
  tests/User.php
Labels: cla/signed
