Repository Icinga/ipl-orm, pull requests merged in 2022-11, with the labels that each got.

#84 Add BoolCast behavior
  src/Behavior/BoolCast.php
  tests/Behavior/BoolCastTest.php
Labels: enhancement, cla/signed

#87 BoolCast: Don't raise an error when `y,n,*` or `null` is passed
  src/Behavior/BoolCast.php
  tests/Behavior/BoolCastTest.php
Labels: cla/signed

#85 Fix selection of expressions referencing relations
  src/Resolver.php
  tests/ResolverTest.php
  tests/TestModelWithExpressions.php
  tests/TestModelWithMoreExpressions.php
Labels: bug, cla/signed
